name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # chạy hằng ngày
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push Snake files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist"
